name: Build and Test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
          
      - name: Run Unit Tests
        run: |
          npm install
          npm run build
          npm run test
          
      - name: Push build to branch
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: "build/*"
          
